"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */

import * as Tabs from "@radix-ui/react-tabs";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, ArrowDown, ArrowUp, Eye, Plus, Rocket, Save, Trash2 } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { articleCategoriesApi, articlesApi } from "@/lib/admin-api/resources";
import type { Article, ArticleBlock } from "@/lib/admin-api/types";
import { DataTable, EmptyState, ErrorState, PageHeader, StatusBadge } from "./AdminUI";
import { CoverImageField } from "./CampaignPages";
import type { ColumnDef } from "@tanstack/react-table";

const field = "w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-secondary";
const empty = { categoryId: "", slug: "", title: "", excerpt: "", authorName: "Admin Derma Nusantara", readTimeMinutes: 5, coverImageUrl: "", coverImageAlt: "", coverImageCaption: "", content: [{ type: "paragraph", text: "" }] as ArticleBlock[], disbursedAmount: "", beneficiaryCount: "", beneficiaryUnit: "", ctaTitle: "", ctaDescription: "", ctaStartingAmount: "", ctaVerificationTime: "", ctaButtonLabel: "", ctaUrl: "", seoTitle: "", seoDescription: "", ogImageUrl: "" };

export function ArticleListPage() {
  const qc = useQueryClient(); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [category, setCategory] = useState(""); const [page, setPage] = useState(1);
  const categories = useQuery({ queryKey: ["article-categories"], queryFn: () => articleCategoriesApi.list() });
  const query = useQuery({ queryKey: ["articles", search, status, category, page], queryFn: () => articlesApi.list({ search, status, category, page, limit: 10 }) });
  const action = useMutation({ mutationFn: async ({ article, name, publishedAt }: { article: Article; name: string; publishedAt?: string }) => { if (name === "delete") await articlesApi.remove(article.id, article.updatedAt); else await articlesApi.action(article.id, name, { expectedUpdatedAt: article.updatedAt, publishedAt }); }, onSuccess: () => qc.invalidateQueries({ queryKey: ["articles"] }) });
  const columns = useMemo<ColumnDef<Article>[]>(() => [
    { accessorKey: "title", header: "Artikel", cell: ({ row }) => <div><Link className="font-semibold text-primary hover:underline" href={`/admin/konten/artikel/${row.original.id}`}>{row.original.title}</Link><p className="text-xs text-slate-500">/{row.original.slug}</p></div> },
    { accessorKey: "category.name", header: "Kategori", cell: ({ row }) => row.original.category.name },
    { accessorKey: "status", header: "Status", cell: ({ row }) => <StatusBadge status={row.original.status} /> },
    { accessorKey: "publishedAt", header: "Publikasi", cell: ({ row }) => row.original.publishedAt ? new Intl.DateTimeFormat("id-ID", { dateStyle: "medium", timeStyle: "short" }).format(new Date(row.original.publishedAt)) : "—" },
    { id: "actions", header: "Aksi", cell: ({ row }) => <div className="flex gap-2">
      <Link title="Preview" target="_blank" href={`/berita/${row.original.slug}`} className="admin-button"><Eye size={15}/></Link>
      {row.original.status === "DRAFT" && <button title="Publish/jadwalkan" className="admin-button" onClick={() => { const publishedAt=prompt("Waktu publikasi ISO (kosong = sekarang)", new Date().toISOString())||undefined; action.mutate({ article: row.original, name: "publish", publishedAt }); }}><Rocket size={15}/></button>}
      {row.original.status === "PUBLISHED" && <button title="Arsipkan" className="admin-button" onClick={() => action.mutate({ article: row.original, name: "archive" })}><Archive size={15}/></button>}
      {row.original.status === "ARCHIVED" && <button className="admin-button" onClick={() => action.mutate({ article: row.original, name: "restore-draft" })}>Draft</button>}
      <button title="Hapus permanen" className="admin-button text-red-600" onClick={() => { const confirmation=window.prompt(`Hapus permanen artikel “${row.original.title}”?\n\nData tidak dapat dipulihkan. Ketik HAPUS untuk melanjutkan.`); if(confirmation==="HAPUS") action.mutate({ article: row.original, name: "delete" }); }}><Trash2 size={15}/></button>
    </div> },
  ], [action]);
  return <section><PageHeader title="Artikel" description="Archive menyembunyikan artikel dari publik tanpa menghapus data. Hapus permanen menghilangkan data dan tidak dapat dipulihkan." actions={<Link className="admin-button admin-button-primary" href="/admin/konten/artikel/baru"><Plus size={17}/>Artikel baru</Link>}/>
    <div className="mb-5 grid gap-3 rounded-2xl bg-white p-4 shadow-sm md:grid-cols-3"><input className={field} placeholder="Cari judul atau slug…" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }}/><select className={field} value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Semua status</option><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select><select className={field} value={category} onChange={(e) => setCategory(e.target.value)}><option value="">Semua kategori</option>{categories.data?.data.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
    {action.isError&&<div className="mb-4"><ErrorState error={action.error}/></div>}{query.isError ? <ErrorState error={query.error} onRetry={() => query.refetch()}/> : query.data?.data.length === 0 ? <EmptyState title="Belum ada artikel" description="Buat artikel pertama Anda."/> : <><DataTable columns={columns} data={query.data?.data ?? []} loading={query.isLoading}/><div className="mt-4 flex justify-end gap-2"><button className="admin-button" disabled={page === 1} onClick={() => setPage(p => p - 1)}>Sebelumnya</button><span className="px-3 py-2 text-sm">Halaman {page}</span><button className="admin-button" disabled={page >= (query.data?.meta?.totalPages ?? 1)} onClick={() => setPage(p => p + 1)}>Berikutnya</button></div></>}</section>;
}

function BlockEditor({ blocks, onChange }: { blocks: ArticleBlock[]; onChange: (v: ArticleBlock[]) => void }) {
  const update = (i: number, patch: object) => onChange(blocks.map((b, x) => x === i ? { ...b, ...patch } as ArticleBlock : b));
  const move = (i: number, d: number) => { const next = [...blocks]; const [item] = next.splice(i, 1); next.splice(i + d, 0, item); onChange(next); };
  return <div className="space-y-3">{blocks.map((b, i) => <div className="rounded-xl border bg-slate-50 p-3" key={i}><div className="mb-2 flex items-center justify-between"><select className={field} value={b.type} onChange={e => update(i, e.target.value === "image" ? { type: "image", url: "", alt: "" } : { type: e.target.value, text: "", ...(e.target.value === "heading" ? { level: 2 } : {}) })}><option value="paragraph">Paragraf</option><option value="heading">Heading</option><option value="quote">Kutipan</option><option value="image">Gambar</option></select><div className="ml-2 flex"><button type="button" disabled={!i} onClick={() => move(i,-1)}><ArrowUp/></button><button type="button" disabled={i === blocks.length-1} onClick={() => move(i,1)}><ArrowDown/></button><button type="button" onClick={() => onChange(blocks.filter((_,x)=>x!==i))}><Trash2/></button></div></div>{b.type === "image" ? <div className="grid gap-2"><input className={field} placeholder="URL gambar" value={b.url} onChange={e=>update(i,{url:e.target.value})}/><input className={field} placeholder="Alt gambar" value={b.alt} onChange={e=>update(i,{alt:e.target.value})}/><input className={field} placeholder="Caption (opsional)" value={b.caption ?? ""} onChange={e=>update(i,{caption:e.target.value})}/></div> : <textarea className={field} rows={b.type === "paragraph" ? 5 : 2} value={b.text} onChange={e=>update(i,{text:e.target.value})}/>}</div>)}<button type="button" className="admin-button" onClick={() => onChange([...blocks,{type:"paragraph",text:""}])}><Plus size={16}/>Tambah blok</button></div>;
}

export function ArticleEditorPage({ id }: { id?: string }) {
  const router = useRouter(); const [form,setForm]=useState<any>(empty); const [dirty,setDirty]=useState(false); const [message,setMessage]=useState("");
  const detail=useQuery({queryKey:["article",id],queryFn:()=>articlesApi.get(id!),enabled:Boolean(id)}); const categories=useQuery({queryKey:["article-categories"],queryFn:()=>articleCategoriesApi.list()});
  useEffect(()=>{if(detail.data?.data){setForm({...empty,...detail.data.data,disbursedAmount:detail.data.data.disbursedAmount ?? "",beneficiaryCount:detail.data.data.beneficiaryCount ?? "",ctaStartingAmount:detail.data.data.ctaStartingAmount ?? ""});setDirty(false)}},[detail.data]);
  useEffect(()=>{const fn=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault()};addEventListener("beforeunload",fn);return()=>removeEventListener("beforeunload",fn)},[dirty]);
  const effectiveOgImageUrl=form.ogImageUrl?.trim()||form.coverImageUrl?.trim()||"";
  const save=useMutation({mutationFn:()=>{const payload={categoryId:form.categoryId,slug:form.slug,title:form.title,excerpt:form.excerpt,authorName:form.authorName,readTimeMinutes:Number(form.readTimeMinutes),coverImageUrl:form.coverImageUrl,coverImageAlt:form.coverImageAlt,coverImageCaption:form.coverImageCaption||undefined,content:form.content,disbursedAmount:form.disbursedAmount===""?undefined:Number(form.disbursedAmount),beneficiaryCount:form.beneficiaryCount===""?undefined:Number(form.beneficiaryCount),beneficiaryUnit:form.beneficiaryUnit||undefined,ctaTitle:form.ctaTitle||undefined,ctaDescription:form.ctaDescription||undefined,ctaStartingAmount:form.ctaStartingAmount===""?undefined:Number(form.ctaStartingAmount),ctaVerificationTime:form.ctaVerificationTime||undefined,ctaButtonLabel:form.ctaButtonLabel||undefined,ctaUrl:form.ctaUrl||undefined,seoTitle:form.seoTitle||undefined,seoDescription:form.seoDescription||undefined,ogImageUrl:effectiveOgImageUrl||undefined,expectedUpdatedAt:detail.data?.data.updatedAt};return id?articlesApi.update(id,payload):articlesApi.create(payload)},onSuccess:r=>{setDirty(false);setMessage("Artikel tersimpan.");if(!id)router.replace(`/admin/konten/artikel/${r.data.id}`)},onError:(e:Error)=>setMessage(e.message)});
  const set=(key:string,value:any)=>{setForm((f:any)=>({...f,[key]:value}));setDirty(true)};
  return <section><PageHeader title={id?"Edit Artikel":"Artikel Baru"} description={dirty?"Ada perubahan yang belum disimpan.":"Editor konten terstruktur dan metadata SEO."} actions={<button className="admin-button admin-button-primary" disabled={save.isPending} onClick={()=>save.mutate()}><Save size={17}/>Simpan draft</button>}/>{message&&<p className="mb-4 rounded-xl bg-white p-3 text-sm">{message}</p>}
    <Tabs.Root defaultValue="info"><Tabs.List className="mb-5 flex flex-wrap gap-2">{[["info","Informasi"],["content","Konten"],["impact","Dampak & CTA"],["seo","SEO"]].map(([v,l])=><Tabs.Trigger className="admin-button data-[state=active]:bg-primary data-[state=active]:text-white" value={v} key={v}>{l}</Tabs.Trigger>)}</Tabs.List>
      <Tabs.Content value="info" className="grid gap-4 rounded-2xl bg-white p-5 md:grid-cols-2"><label>Kategori<select required className={field} value={form.categoryId} onChange={e=>set("categoryId",e.target.value)}><option value="">Pilih kategori</option>{categories.data?.data.filter(c=>c.isActive).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Slug<input required className={field} value={form.slug} onChange={e=>set("slug",e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""))}/></label><label className="md:col-span-2">Judul<input required maxLength={180} className={field} value={form.title} onChange={e=>set("title",e.target.value)}/></label><label className="md:col-span-2">Excerpt<textarea required maxLength={500} className={field} value={form.excerpt} onChange={e=>set("excerpt",e.target.value)}/></label><label>Penulis<input required className={field} value={form.authorName} onChange={e=>set("authorName",e.target.value)}/></label><label>Waktu baca (menit)<input type="number" min="1" className={field} value={form.readTimeMinutes} onChange={e=>set("readTimeMinutes",e.target.value)}/></label><CoverImageField className="md:col-span-2" url={form.coverImageUrl} alt={form.coverImageAlt} onUrlChange={value=>set("coverImageUrl",value)} onAltChange={value=>set("coverImageAlt",value)}/><label className="md:col-span-2">Caption cover (opsional)<input maxLength={300} className={field} value={form.coverImageCaption??""} onChange={e=>set("coverImageCaption",e.target.value)}/></label></Tabs.Content>
      <Tabs.Content value="content" className="rounded-2xl bg-white p-5"><BlockEditor blocks={form.content} onChange={v=>set("content",v)}/></Tabs.Content>
      <Tabs.Content value="impact" className="grid gap-4 rounded-2xl bg-white p-5 md:grid-cols-2">{[["disbursedAmount","Dana tersalurkan"],["beneficiaryCount","Jumlah penerima"],["beneficiaryUnit","Satuan penerima"],["ctaTitle","Judul CTA"],["ctaDescription","Deskripsi CTA"],["ctaStartingAmount","Nominal awal"],["ctaVerificationTime","Waktu verifikasi"],["ctaButtonLabel","Label tombol"],["ctaUrl","URL tujuan"]].map(([k,l])=><label key={k}>{l}<input className={field} value={form[k]??""} onChange={e=>set(k,e.target.value)}/></label>)}</Tabs.Content>
      <Tabs.Content value="seo" className="space-y-4 rounded-2xl bg-white p-5"><label>SEO title ({(form.seoTitle||form.title).length}/70)<input maxLength={70} className={field} value={form.seoTitle??""} onChange={e=>set("seoTitle",e.target.value)}/></label><label>SEO description<textarea maxLength={160} className={field} value={form.seoDescription??""} onChange={e=>set("seoDescription",e.target.value)}/></label><label>OG image URL<input className={field} type="url" value={form.ogImageUrl||form.coverImageUrl||""} onChange={e=>set("ogImageUrl",e.target.value)}/><span className="mt-1 block text-xs text-slate-500">{form.ogImageUrl?.trim()?"Menggunakan gambar khusus untuk media sosial.":form.coverImageUrl?"Otomatis menggunakan URL cover dari tab Informasi.":"Isi cover pada tab Informasi atau masukkan URL gambar khusus."}</span></label>{effectiveOgImageUrl&&<div><p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-500">Preview OG image</p><div role="img" aria-label="Preview OG image artikel" className="aspect-[1.91/1] max-w-xl rounded-xl border border-slate-200 bg-slate-100 bg-cover bg-center" style={{backgroundImage:`url("${effectiveOgImageUrl.replaceAll('"','%22')}")`}}/></div>}<div className="rounded-xl border p-4"><p className="text-lg text-blue-800">{form.seoTitle||form.title||"Judul artikel"}</p><p className="text-sm text-green-700">dermanusantara.my.id/berita/{form.slug}</p><p className="text-sm text-slate-600">{form.seoDescription||form.excerpt}</p></div></Tabs.Content>
    </Tabs.Root></section>;
}

export function ArticleCategoryPage(){
  const qc=useQueryClient();const q=useQuery({queryKey:["article-categories"],queryFn:()=>articleCategoriesApi.list()});const [name,setName]=useState("");const [code,setCode]=useState("");
  const mutate=useMutation({mutationFn:async({kind,id,active}:{kind:string,id?:string,active?:boolean})=>{if(kind==="create")await articleCategoriesApi.create({name,code,isActive:true});else if(kind==="delete")await articleCategoriesApi.remove(id!);else await articleCategoriesApi.toggle(id!,active!)},onSuccess:()=>{setName("");setCode("");qc.invalidateQueries({queryKey:["article-categories"]})}});
  return <section><PageHeader title="Kategori Artikel" description="Kategori nonaktif tidak dapat digunakan untuk publikasi."/><form className="mb-5 flex gap-3 rounded-2xl bg-white p-4" onSubmit={e=>{e.preventDefault();mutate.mutate({kind:"create"})}}><input required className={field} placeholder="Nama" value={name} onChange={e=>{setName(e.target.value);setCode(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-"))}}/><input required className={field} placeholder="kode-kategori" value={code} onChange={e=>setCode(e.target.value)}/><button className="admin-button admin-button-primary">Tambah</button></form><div className="space-y-2">{q.data?.data.map(c=><div className="flex items-center justify-between rounded-xl bg-white p-4" key={c.id}><div><b>{c.name}</b><p className="text-xs text-slate-500">{c.code} · {c._count?.articles??0} artikel</p></div><div className="flex gap-2"><button className="admin-button" onClick={()=>mutate.mutate({kind:"toggle",id:c.id,active:!c.isActive})}>{c.isActive?"Nonaktifkan":"Aktifkan"}</button><button disabled={Boolean(c._count?.articles)} className="admin-button text-red-600" onClick={()=>confirm("Hapus kategori?")&&mutate.mutate({kind:"delete",id:c.id})}>Hapus</button></div></div>)}</div></section>
}
