"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import { useMutation, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, ImagePlus, Link2, UploadCloud } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { mediaApi } from "@/lib/admin-api/resources";

type Props = { url:string; alt:string; onUrlChange:(value:string)=>void; onAltChange:(value:string)=>void; title?:string; description?:string; pickerLabel?:string; previewLabel?:string; urlLabel?:string; required?:boolean; altRequired?:boolean; showAlt?:boolean; className?:string };

export function ImageUploadField({url,alt,onUrlChange,onAltChange,title="Gambar sampul",description="Unggah gambar baru atau gunakan URL gambar yang sudah tersedia.",pickerLabel="Pilih gambar",previewLabel="Preview gambar",urlLabel="URL gambar",required=true,altRequired=true,showAlt=true,className=""}:Props){
 const qc=useQueryClient(), fileRef=useRef<HTMLInputElement>(null); const [mode,setMode]=useState<"upload"|"url">("upload"),[file,setFile]=useState<File>(),[error,setError]=useState<string>(),[localPreview,setLocalPreview]=useState<string>();
 useEffect(()=>{if(!file){setLocalPreview(undefined);return;}const objectUrl=URL.createObjectURL(file);setLocalPreview(objectUrl);return()=>URL.revokeObjectURL(objectUrl)},[file]);
 const upload=useMutation({mutationFn:async()=>{const body=new FormData();body.append("file",file!);return mediaApi.upload(body)},onSuccess:async response=>{onUrlChange(response.data.url);if(!alt.trim()&&file)onAltChange(file.name.replace(/\.[^.]+$/,"").replace(/[-_]+/g," "));setFile(undefined);if(fileRef.current)fileRef.current.value="";await qc.invalidateQueries({queryKey:["admin","media"]})}});
 function select(selected?:File){setError(undefined);upload.reset();if(!selected){setFile(undefined);return}if(!["image/jpeg","image/png","image/webp"].includes(selected.type)){setError("Gunakan gambar JPEG, PNG, atau WebP.");return}if(selected.size>5*1024*1024){setError("Ukuran gambar maksimum 5 MB.");return}setFile(selected)}
 const preview=localPreview??url;
 return <div className={`rounded-2xl border border-slate-200 bg-slate-50/70 p-5 ${className}`}>
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-sm font-bold text-slate-800">{title}{required&&<span className="text-red-600"> *</span>}</h3><p className="mt-1 text-xs text-slate-500">{description}</p></div><div className="inline-flex rounded-xl border border-slate-200 bg-white p-1 shadow-sm"><button type="button" onClick={()=>setMode("upload")} className={`inline-flex min-h-9 items-center gap-2 rounded-lg px-3 text-sm font-semibold ${mode==="upload"?"bg-primary text-white":"text-slate-600"}`}><UploadCloud size={15}/> Upload file</button><button type="button" onClick={()=>setMode("url")} className={`inline-flex min-h-9 items-center gap-2 rounded-lg px-3 text-sm font-semibold ${mode==="url"?"bg-primary text-white":"text-slate-600"}`}><Link2 size={15}/> Gunakan URL</button></div></div>
  <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_280px]"><div>{mode==="upload"?<div className="rounded-xl border-2 border-dashed border-slate-300 bg-white p-5 text-center"><div className="mx-auto flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><ImagePlus size={22}/></div><p className="mt-3 text-sm font-bold text-slate-800">{file?file.name:pickerLabel}</p><p className="mt-1 text-xs text-slate-500">{file?`${(file.size/1024/1024).toFixed(2)} MB`:"JPEG, PNG, atau WebP · maksimum 5 MB"}</p><input ref={fileRef} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>select(e.target.files?.[0])}/><div className="mt-4 flex justify-center gap-2"><button type="button" className="admin-button admin-button-secondary" onClick={()=>fileRef.current?.click()}>Pilih file</button><button type="button" className="admin-button admin-button-primary" disabled={!file||upload.isPending} onClick={()=>upload.mutate()}><UploadCloud size={16}/>{upload.isPending?"Mengunggah…":"Upload & gunakan"}</button></div></div>:<label className="admin-field"><span>{urlLabel}</span><input required={required} placeholder="https://contoh.com/gambar.webp atau /images/gambar.webp" value={url} onChange={e=>onUrlChange(e.target.value)}/><small className="font-normal text-slate-500">URL http(s) publik atau path internal yang diawali /.</small></label>}
  {(error||upload.error?.message)&&<p className="mt-3 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error??upload.error?.message}</p>}{mode==="upload"&&url&&!file&&!upload.isPending&&<p className="mt-3 inline-flex items-center gap-2 text-sm font-semibold text-emerald-700"><CheckCircle2 size={16}/>Gambar berhasil diunggah dan digunakan.</p>}{showAlt&&<label className="admin-field mt-4"><span>Alt gambar{altRequired&&<span className="text-red-600"> *</span>}</span><input required={altRequired} placeholder="Deskripsikan isi gambar untuk aksesibilitas" value={alt} onChange={e=>onAltChange(e.target.value)}/></label>}</div>
  <div><p className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-500">{previewLabel}</p><div role="img" aria-label={alt||previewLabel} className="aspect-[16/10] overflow-hidden rounded-xl border border-slate-200 bg-slate-100 bg-cover bg-center" style={preview?{backgroundImage:`url("${preview.replaceAll('"','%22')}")`}:undefined}>{!preview&&<div className="flex size-full flex-col items-center justify-center gap-2 text-slate-400"><ImagePlus size={28}/><span className="text-xs">Belum ada gambar</span></div>}</div>{url&&<p className="mt-2 break-all text-xs text-slate-500">URL tersimpan: {url}</p>}</div></div>
 </div>
}
